- { repo: ilyachur/cmake4vim }
- { repo: yami-beta/asyncomplete-omni.vim }
- { repo: prabirshrestha/asyncomplete-tags.vim, if: 0 }
- { repo: OmniSharp/omnisharp-vim }
- { repo: machakann/asyncomplete-ezfilter.vim }
- { repo: kana/vim-altr, on_map: { n: <Plug> }}
- repo: lewis6991/spellsitter.nvim
  depends: [ nvim-treesitter ]
  hook_post_source: |-
    lua require('spellsitter').setup()
- repo: ThePrimeagen/refactoring.nvim
  depends: [ nvim-treesitter, plenary.vim ]
  hook_post_source: |-
    lua require('refactoring').setup({})
    lua require('telescope').load_extension("refactoring")
  hook_add: |-
    lua vim.api.nvim_set_keymap("v", "<leader>rr", "<Esc><cmd>lua require('telescope').extensions.refactoring.refactors()<CR>",	{ noremap = true })
- repo: mizlan/iswap.nvim
  depends: [ nvim-treesitter ]
  hook_post_source: |-
    lua require('iswap').setup{}
- repo: fidian/hexmode
- repo: theHamsta/nvim-semantic-tokens
- repo: simrat39/inlay-hints.nvim
#- repo: lvimuser/lsp-inlayhints.nvim
# - { repo: jackguo380/vim-lsp-cxx-highlight }
#- { repo: preservim/tagbar }
#- { repo: vim-airline/vim-airline }
